import {StyleSheet, Dimensions} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export default styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    fontSize: 30,
    color: 'black',
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
  },
  textinput: {
    marginTop: 10,
    backgroundColor: 'rgb(240, 238, 230)',
    borderColor: 'rgb(217, 213, 169)',
    borderWidth: 1,
    marginHorizontal: 10,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 5,
    minHeight: hp(8),
  },
  textinputCoupon: {
    backgroundColor: 'rgb(240, 238, 230)',
    paddingVertical: 10,
    width: wp(85),
  },
  coupon: {
    marginTop: 10,
    backgroundColor: 'rgb(240, 238, 230)',
    borderColor: 'rgb(217, 213, 169)',
    borderWidth: 1,
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingVertical: 10,
    borderRadius: 5,
    maxHeight: hp(10),
    flexDirection: 'row',
  },
  couponCorrect: {
    marginTop: 10,
    backgroundColor: '#38E54D',
    borderColor: 'rgb(217, 213, 169)',
    borderWidth: 1,
    marginHorizontal: 10,
    alignItems: 'center',
    textAlign:'center',
    justifyContent: 'space-evenly',
    paddingVertical: 10,
    borderRadius: 5,
    maxHeight: hp(10),
  },
  couponWrong: {
    marginTop: 10,
    backgroundColor: 'red',
    borderColor: 'rgb(217, 213, 169)',
    borderWidth: 1,
    marginHorizontal: 10,
    alignItems: 'center',
    textAlign:'center',
    justifyContent: 'space-evenly',
    paddingVertical: 10,
    borderRadius: 5,
    maxHeight: hp(10),
  },
  button: {
    width: wp(85),
    alignSelf: 'center',
    margin: hp(0.5) * wp(1),
    height: hp(6),
  },
  couponButton: {
    width: wp(85),
    alignSelf: 'center',
    margin: hp(0.5) * wp(1),
    height: hp(6),
  },
  text: {
    fontSize: 20,
    color: 'black',
  },
  datePick: {
    backgroundColor: 'white',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    margin: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 20,
  },
  datePickInner: {
    flexDirection: 'row',
    margin: 10,
    paddingLeft: 10,
    height: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  datePickText: {
    color: 'red',
    fontSize: 20,
    fontWeight: 'bold',
  },
});
